### PR TITLE
Calendar fix

### PR DESCRIPTION
**Pull request by saumyasinghal747**
Calculate local timezone offsets and move the events properly.

**Important:** There are differences with the way the site will behave when running in development or production. It all depends on the locale of where it was compiled.

&lt;the earlier testing comment was before I merged the new commits, but please test this across timezones&gt;

Also fixes some things like cloning that were already fixed after the previous merge, so this PR is likely to confuse Github a little.

### CODE REVIEW

**Comment by kisonecat** [comment]
Are the times presented on https://circlez.rossprogram.org/calendar/ not correct for folks in pacific or other non-Eastern timezones?

**Comment by kisonecat** [comment]
I see -- it seems that the red line is in the local time, but the events are presented in Eastern.  Let me look at this to see if this PR will fix this...

**Comment by kisonecat** [comment]
I've deployed a slightly different version of this code now.  Could you visit https://circlez.rossprogram.org/calendar and let me know if it is working?

**Comment by saumyasinghal747** [comment]
I see in devtools that the code has changed, but the functionality has not. I am still experiencing the same issue. Running my fork does work, and I also tested it using Chrome's timezone simulator, and it looks like people in Shanghai or Berlin (or any other timezone, I assume) would not experience the issue,

**Comment by kisonecat** [comment]
I also used a timezone simulator within Chromium, and got different results from that simulator than from running `TZ=America/Pacific chromium` which I found quite disturbing.  It seems that setting the environment variable is replicating the behavior that people in other timezones were seeing.

https://github.com/rossprogram/circle-z-frontend/commit/ec1b4cfd62ceb03ebd812f9bb84589a23a180482 should fix the problems by using
```
if (event.startDate.zone.tzid === 'floating') {
	    event.startDate.zone = new ICAL.Timezone(vtimezone);
}
event.startDate.addDuration(new ICAL.Duration({ hours: 0 }));
```
to replace the 'floating' timezone with the correct timezone.   After making that change, when I view the pages under `TZ=America/Pacific chromium` it is working, as well as in my local timezone.

**Comment by saumyasinghal747** [comment]
Yes! I can confirm that the calendar on Circle Z is displaying correctly for PST users.  I also double-checked with a friend.

**Comment by kisonecat** [comment]
Great! I am glad to hear it.

**Pull request merged**
